version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
  commands:
    - pip install -e .[docs]
    - python scripts/gen_ref_pages.py
    - mkdocs build --site-dir $READTHEDOCS_OUTPUT/html

# mkdocs:
#   configuration: mkdocs.yml

# python:
#   install:
#     - method: pip
#       path: .
#       extra_requirements:
#         - docs
