site_name: Ragas
#site_url: https://jjmachan.github.io/ragasDocs
repo_name: explodinggradients/ragas
repo_url: https://github.com/explodinggradients/ragas
exclude_docs: |
  howtos/*
  reference/*


# Navigation
nav:
  - "": index.md
  - 🚀 Get Started: 
    - getstarted/index.md
    - Installation: getstarted/install.md
    - Generate a Synthetic Testset: getstarted/testset_generation.md
    - Evaluate Using Your Testset: getstarted/evaluation.md
    - Monitor Your RAG in Production: getstarted/monitoring.md
  - 📚 Core Concepts: 
    - concepts/index.md
    - Evaluation Driven Development: concepts/evaluation_driven.md
    - Metrics: 
      - concepts/metrics/index.md
      - Faithfulness: concepts/metrics/faithfulness.md
      - Answer Relevance: concepts/metrics/answer_relevance.md
      - Context Recall: concepts/metrics/context_recall.md
      - Context Precision: concepts/metrics/context_precision.md
      - Context Utilization: concepts/metrics/context_utilization.md
      - Context Entities Recall: concepts/metrics/context_entities_recall.md
      - Noise Sensitivity: concepts/metrics/noise_sensitivity.md
      - Summarization Score: concepts/metrics/summarization_score.md
      - Answer Correctness: concepts/metrics/answer_correctness.md
      - Answer Semantic Similarity: concepts/metrics/semantic_similarity.md
    - Synthetic Test Data Generation: concepts/testset_generation.md
    - Prompt Object: concepts/prompts.md
    - Prompt Adaptation: concepts/prompt_adaptation.md
    - Utilizing User Feedback: concepts/feedback.md
  - 🛠️ How-to Guides: howtos/index.md
  - 📖 References: reference/index.md
  - ❤️ Community: community/index.md

# Material-Docs Theme
theme:
  name: material
  logo: _static/imgs/ragas-logo.png
  favicon: _static/favicon.ico
  palette:
    scheme: slate
    accent: white
  features:
    - content.tabs.link
    - content.code.annotate
    - content.code.copy
    - announce.dismiss
    - navigation.tabs
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.path
    - navigation.sections
    - navigation.top
    - navigation.tracking
    - navigation.indexes
    - search.suggest
    - search.highlight
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - admonition
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - attr_list
  - md_in_html
  - pymdownx.arithmatex:
      generic: true

# Extra CSS
extra_css:
  - extra/style.css

# Plugins
extra:
  version:
    provider: mike
plugins:
  - search
  - mkdocstrings
  - mike:
      alias_type: symlink
      redirect_template: null
      deploy_prefix: ''
      canonical_version: null
      version_selector: true
      css_dir: css
      javascript_dir: js
  - mkdocs-jupyter:
      execute: false
      include: ["*.ipynb"]
      ignore: ["*"]

      jupyter_options:
        hide_input: false
        hide_output: false
        code_folding: true
        code_line_numbers: true
        jupyter_images: true
        jupyter_table_beautifier: true
  - glightbox

extra_javascript:
  - _static/js/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js